// File generated by FlutterFire CLI.
// This is a template - you need to replace with your actual Firebase configuration
// Run: flutterfire configure (after installing Firebase CLI)

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrTkEJOhnwnNRJx3v6ogKtYO5ZxNgw7dY',
    appId: '1:1014976329990:android:cf3b26249991f789b0c687',
    messagingSenderId: '1014976329990',
    projectId: 'learnxai',
    storageBucket: 'learnxai.firebasestorage.app',
  );

  // TODO: Replace with your actual Android configuration from Firebase Console

  // TODO: Replace with your actual iOS configuration from Firebase Console
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // From GoogleService-Info.plist
    appId: 'YOUR_IOS_APP_ID', // From GoogleService-Info.plist
    messagingSenderId: 'YOUR_SENDER_ID', // From GoogleService-Info.plist
    projectId: 'YOUR_PROJECT_ID', // From Firebase Console
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.edtechApp',
  );

  // TODO: Replace with your actual Web configuration from Firebase Console
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}
